### ISSUE TITLE
fast_bleu Installation

### ISSUE THREAD

**Issue by kinal1999** [rajpurkarlab/CXR-Report-Metric#1]
Unable to install the requirements in order to run the program. Any solutions?

(myenv) kinal@Kinals-MacBook-Air CXR-Report-Metric-main % pip install -r requirements.txt
Collecting allennlp==1.1.0 (from -r requirements.txt (line 1))
  Using cached allennlp-1.1.0-py3-none-any.whl (485 kB)
Collecting allennlp_models==1.1.0 (from -r requirements.txt (line 2))
  Using cached allennlp_models-1.1.0-py3-none-any.whl (322 kB)
Collecting beautifulsoup4==4.8.1 (from -r requirements.txt (line 3))
  Using cached beautifulsoup4-4.8.1-py3-none-any.whl (101 kB)
Collecting bert-score==0.3.11 (from -r requirements.txt (line 4))
  Using cached bert_score-0.3.11-py3-none-any.whl (60 kB)
Collecting fast-bleu==0.0.90 (from -r requirements.txt (line 5))
  Using cached fast-bleu-0.0.90.tar.gz (14 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting lxml (from -r requirements.txt (line 6))
  Using cached lxml-4.9.2-cp39-cp39-macosx_10_15_x86_64.whl (4.8 MB)
Collecting numpy==1.18.2 (from -r requirements.txt (line 7))
  Using cached numpy-1.18.2.zip (5.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [198 lines of output]
      Running from numpy source directory.
      <string>:461: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
      /private/var/folders/pj/4nm1288n4rxd04t1f67hk8cm0000gn/T/pip-install-tdit1xs0/numpy_e9879434578b4ba18fa5ac06a576db5a/tools/cythonize.py:75: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        required_version = LooseVersion('0.29.14')
      /private/var/folders/pj/4nm1288n4rxd04t1f67hk8cm0000gn/T/pip-install-tdit1xs0/numpy_e9879434578b4ba18fa5ac06a576db5a/tools/cythonize.py:77: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        if LooseVersion(cython_version) < required_version:
      Processing numpy/random/_bounded_integers.pxd.in
      Processing numpy/random/_philox.pyx
      Processing numpy/random/_bit_generator.pyx
      Processing numpy/random/_bounded_integers.pyx.in
      Processing numpy/random/_sfc64.pyx
      Processing numpy/random/_mt19937.pyx
      Processing numpy/random/mtrand.pyx
      Processing numpy/random/_generator.pyx
      Processing numpy/random/_pcg64.pyx
      Processing numpy/random/_common.pyx
      Cythonizing sources
      blas_opt_info:
      blas_mkl_info:
      customize UnixCCompiler
        libraries mkl_rt not found in ['/Library/Frameworks/Python.framework/Versions/3.9/lib', '/usr/local/lib', '/usr/lib']
        NOT AVAILABLE
      
      blis_info:
        libraries blis not found in ['/Library/Frameworks/Python.framework/Versions/3.9/lib', '/usr/local/lib', '/usr/lib']
        NOT AVAILABLE
      
      openblas_info:
        libraries openblas not found in ['/Library/Frameworks/Python.framework/Versions/3.9/lib', '/usr/local/lib', '/usr/lib']
        NOT AVAILABLE
      
      atlas_3_10_blas_threads_info:
      Setting PTATLAS=ATLAS
        libraries tatlas not found in ['/Library/Frameworks/Python.framework/Versions/3.9/lib', '/usr/local/lib', '/usr/lib']
        NOT AVAILABLE
      
      atlas_3_10_blas_info:
        libraries satlas not found in ['/Library/Frameworks/Python.framework/Versions/3.9/lib', '/usr/local/lib', '/usr/lib']
        NOT AVAILABLE
      
      atlas_blas_threads_info:
      Setting PTATLAS=ATLAS
        libraries ptf77blas,ptcblas,atlas not found in ['/Library/Frameworks/Python.framework/Versions/3.9/lib', '/usr/local/lib', '/usr/lib']
        NOT AVAILABLE
      
      atlas_blas_info:
        libraries f77blas,cblas,atlas not found in ['/Library/Frameworks/Python.framework/Versions/3.9/lib', '/usr/local/lib', '/usr/lib']
        NOT AVAILABLE
      
      accelerate_info:
        libraries accelerate not found in ['/Library/Frameworks/Python.framework/Versions/3.9/lib', '/usr/local/lib', '/usr/lib']
      Library accelerate was not found. Ignoring
        libraries veclib not found in ['/Library/Frameworks/Python.framework/Versions/3.9/lib', '/usr/local/lib', '/usr/lib']
      Library veclib was not found. Ignoring
        FOUND:
          extra_compile_args = ['-msse3', '-I/System/Library/Frameworks/vecLib.framework/Headers']
          extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
          define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]
      
        FOUND:
          extra_compile_args = ['-msse3', '-I/System/Library/Frameworks/vecLib.framework/Headers']
          extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
          define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]
      
      non-existing path in 'numpy/distutils': 'site.cfg'
      lapack_opt_info:
      lapack_mkl_info:
        libraries mkl_rt not found in ['/Library/Frameworks/Python.framework/Versions/3.9/lib', '/usr/local/lib', '/usr/lib']
        NOT AVAILABLE
      
      openblas_lapack_info:
        libraries openblas not found in ['/Library/Frameworks/Python.framework/Versions/3.9/lib', '/usr/local/lib', '/usr/lib']
        NOT AVAILABLE
      
      openblas_clapack_info:
        libraries openblas,lapack not found in ['/Library/Frameworks/Python.framework/Versions/3.9/lib', '/usr/local/lib', '/usr/lib']
        NOT AVAILABLE
      
      flame_info:
        libraries flame not found in ['/Library/Frameworks/Python.framework/Versions/3.9/lib', '/usr/local/lib', '/usr/lib']
        NOT AVAILABLE
      
      atlas_3_10_threads_info:
      Setting PTATLAS=ATLAS
        libraries lapack_atlas not found in /Library/Frameworks/Python.framework/Versions/3.9/lib
        libraries tatlas,tatlas not found in /Library/Frameworks/Python.framework/Versions/3.9/lib
        libraries lapack_atlas not found in /usr/local/lib
        libraries tatlas,tatlas not found in /usr/local/lib
        libraries lapack_atlas not found in /usr/lib
        libraries tatlas,tatlas not found in /usr/lib
      <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
        NOT AVAILABLE
      
      atlas_3_10_info:
        libraries lapack_atlas not found in /Library/Frameworks/Python.framework/Versions/3.9/lib
        libraries satlas,satlas not found in /Library/Frameworks/Python.framework/Versions/3.9/lib
        libraries lapack_atlas not found in /usr/local/lib
        libraries satlas,satlas not found in /usr/local/lib
        libraries lapack_atlas not found in /usr/lib
        libraries satlas,satlas not found in /usr/lib
      <class 'numpy.distutils.system_info.atlas_3_10_info'>
        NOT AVAILABLE
      
      atlas_threads_info:
      Setting PTATLAS=ATLAS
        libraries lapack_atlas not found in /Library/Frameworks/Python.framework/Versions/3.9/lib
        libraries ptf77blas,ptcblas,atlas not found in /Library/Frameworks/Python.framework/Versions/3.9/lib
        libraries lapack_atlas not found in /usr/local/lib
        libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
        libraries lapack_atlas not found in /usr/lib
        libraries ptf77blas,ptcblas,atlas not found in /usr/lib
      <class 'numpy.distutils.system_info.atlas_threads_info'>
        NOT AVAILABLE
      
      atlas_info:
        libraries lapack_atlas not found in /Library/Frameworks/Python.framework/Versions/3.9/lib
        libraries f77blas,cblas,atlas not found in /Library/Frameworks/Python.framework/Versions/3.9/lib
        libraries lapack_atlas not found in /usr/local/lib
        libraries f77blas,cblas,atlas not found in /usr/local/lib
        libraries lapack_atlas not found in /usr/lib
        libraries f77blas,cblas,atlas not found in /usr/lib
      <class 'numpy.distutils.system_info.atlas_info'>
        NOT AVAILABLE
      
        FOUND:
          extra_compile_args = ['-msse3', '-I/System/Library/Frameworks/vecLib.framework/Headers']
          extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
          define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]
      
      /private/var/folders/pj/4nm1288n4rxd04t1f67hk8cm0000gn/T/pip-build-env-jd0r0z4_/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py:265: UserWarning: Unknown distribution option: 'define_macros'
        warnings.warn(msg)
      running dist_info
      running build_src
      build_src
      building py_modules sources
      creating build
      creating build/src.macosx-10.9-x86_64-3.9
      creating build/src.macosx-10.9-x86_64-3.9/numpy
      creating build/src.macosx-10.9-x86_64-3.9/numpy/distutils
      building library "npymath" sources
      gfortran: warning: this compiler does not support x86 ('-arch' option ignored)
      gfortran: warning: this compiler does not support x86 ('-arch' option ignored)
      gfortran: warning: this compiler does not support x86 ('-arch' option ignored)
      gfortran: warning: this compiler does not support x86 ('-arch' option ignored)
      gfortran: warning: this compiler does not support x86 ('-arch' option ignored)
      gfortran: warning: this compiler does not support x86 ('-arch' option ignored)
      gfortran: warning: this compiler does not support x86 ('-arch' option ignored)
      gfortran: warning: this compiler does not support x86 ('-arch' option ignored)
      Traceback (most recent call last):
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/private/var/folders/pj/4nm1288n4rxd04t1f67hk8cm0000gn/T/pip-build-env-jd0r0z4_/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 380, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/private/var/folders/pj/4nm1288n4rxd04t1f67hk8cm0000gn/T/pip-build-env-jd0r0z4_/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/private/var/folders/pj/4nm1288n4rxd04t1f67hk8cm0000gn/T/pip-build-env-jd0r0z4_/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 488, in <module>
        File "<string>", line 480, in setup_package
        File "/private/var/folders/pj/4nm1288n4rxd04t1f67hk8cm0000gn/T/pip-install-tdit1xs0/numpy_e9879434578b4ba18fa5ac06a576db5a/numpy/distutils/core.py", line 171, in setup
          return old_setup(**new_attr)
        File "/private/var/folders/pj/4nm1288n4rxd04t1f67hk8cm0000gn/T/pip-build-env-jd0r0z4_/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/private/var/folders/pj/4nm1288n4rxd04t1f67hk8cm0000gn/T/pip-build-env-jd0r0z4_/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/private/var/folders/pj/4nm1288n4rxd04t1f67hk8cm0000gn/T/pip-build-env-jd0r0z4_/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/private/var/folders/pj/4nm1288n4rxd04t1f67hk8cm0000gn/T/pip-build-env-jd0r0z4_/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/private/var/folders/pj/4nm1288n4rxd04t1f67hk8cm0000gn/T/pip-build-env-jd0r0z4_/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1244, in run_command
          super().run_command(command)
        File "/private/var/folders/pj/4nm1288n4rxd04t1f67hk8cm0000gn/T/pip-build-env-jd0r0z4_/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/pj/4nm1288n4rxd04t1f67hk8cm0000gn/T/pip-build-env-jd0r0z4_/overlay/lib/python3.9/site-packages/setuptools/command/dist_info.py", line 99, in run
          self.egg_info.run()
        File "/private/var/folders/pj/4nm1288n4rxd04t1f67hk8cm0000gn/T/pip-install-tdit1xs0/numpy_e9879434578b4ba18fa5ac06a576db5a/numpy/distutils/command/egg_info.py", line 26, in run
          self.run_command("build_src")
        File "/private/var/folders/pj/4nm1288n4rxd04t1f67hk8cm0000gn/T/pip-build-env-jd0r0z4_/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/private/var/folders/pj/4nm1288n4rxd04t1f67hk8cm0000gn/T/pip-build-env-jd0r0z4_/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1244, in run_command
          super().run_command(command)
        File "/private/var/folders/pj/4nm1288n4rxd04t1f67hk8cm0000gn/T/pip-build-env-jd0r0z4_/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/pj/4nm1288n4rxd04t1f67hk8cm0000gn/T/pip-install-tdit1xs0/numpy_e9879434578b4ba18fa5ac06a576db5a/numpy/distutils/command/build_src.py", line 146, in run
          self.build_sources()
        File "/private/var/folders/pj/4nm1288n4rxd04t1f67hk8cm0000gn/T/pip-install-tdit1xs0/numpy_e9879434578b4ba18fa5ac06a576db5a/numpy/distutils/command/build_src.py", line 157, in build_sources
          self.build_library_sources(*libname_info)
        File "/private/var/folders/pj/4nm1288n4rxd04t1f67hk8cm0000gn/T/pip-install-tdit1xs0/numpy_e9879434578b4ba18fa5ac06a576db5a/numpy/distutils/command/build_src.py", line 290, in build_library_sources
          sources = self.generate_sources(sources, (lib_name, build_info))
        File "/private/var/folders/pj/4nm1288n4rxd04t1f67hk8cm0000gn/T/pip-install-tdit1xs0/numpy_e9879434578b4ba18fa5ac06a576db5a/numpy/distutils/command/build_src.py", line 380, in generate_sources
          source = func(extension, build_dir)
        File "numpy/core/setup.py", line 661, in get_mathlib_info
          raise RuntimeError("Broken toolchain: cannot link a simple C program")
      RuntimeError: Broken toolchain: cannot link a simple C program
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by KathyFeiyang** [comment]
Thanks for raising this issue. Could you try creating a fresh conda environment with Python 3.7 and then installing dependencies using requirements.txt? The dependencies can be tricky to set up correctly and we have found this approach to be the easiest.

**Comment by Asaad-Pak** [comment]
fast-bleu can't be installed in windows or anaconda environment. you need to install wsl and ubuntu 20.04 as distribution and then install fast bleu there.
